# Najprostszy model

* Wykorzystanie tylko atrybutów numerycznych
* Porównanie regresji liniowej z modelem losowym
  * U(0,5) i U(4,5)

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import numpy as np
%matplotlib inline

DATA_VERSION = "v2"

calendar = pd.read_csv(f'../data/{DATA_VERSION}/raw/calendar.csv')
listings = pd.read_csv(f'../data/{DATA_VERSION}/raw/listings.csv')
reviews = pd.read_csv(f'../data/{DATA_VERSION}/raw/reviews.csv')

In [16]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13984 entries, 0 to 13983
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            13984 non-null  int64
 1   listing_url                                   13984 non-null  object
 2   scrape_id                                     13984 non-null  int64
 3   last_scraped                                  13984 non-null  object
 4   source                                        13984 non-null  object
 5   name                                          13984 non-null  object
 6   description                                   13365 non-null  object
 7   neighborhood_overview                         6791 non-null   object
 8   picture_url                                   13984 non-null  object
 9   host_id                                       13984 non-null  int64
 10  host_url                                      13984 non-null  object
 11  host_name                                     13975 non-null  object
 12  host_since                                    13975 non-null  object
 13  host_location                                 11325 non-null  object
 14  host_about                                    7193 non-null   object
 15  host_response_time                            8656 non-null   object
 16  host_response_rate                            8656 non-null   object
 17  host_acceptance_rate                          9447 non-null   object
 18  host_is_superhost                             13847 non-null  object
 19  host_thumbnail_url                            13975 non-null  object
 20  host_picture_url                              13975 non-null  object
 21  host_neighbourhood                            6097 non-null   object
 22  host_listings_count                           13975 non-null  float64
 23  host_total_listings_count                     13975 non-null  float64
 24  host_verifications                            13975 non-null  object
 25  host_has_profile_pic                          13975 non-null  object
 26  host_identity_verified                        13975 non-null  object
 27  neighbourhood                                 6791 non-null   object
 28  neighbourhood_cleansed                        13984 non-null  object
 29  neighbourhood_group_cleansed                  13984 non-null  object
 30  latitude                                      13984 non-null  float64
 31  longitude                                     13984 non-null  float64
 32  property_type                                 13984 non-null  object
 33  room_type                                     13984 non-null  object
 34  accommodates                                  13984 non-null  int64
 35  bathrooms                                     9002 non-null   float64
 36  bathrooms_text                                13977 non-null  object
 37  bedrooms                                      11924 non-null  float64
 38  beds                                          8971 non-null   float64
 39  amenities                                     13984 non-null  object
 40  price                                         8990 non-null   object
 41  minimum_nights                                13984 non-null  int64
 42  maximum_nights                                13984 non-null  int64
 43  minimum_minimum_nights                        13984 non-null  int64
 44  maximum_minimum_nights                        13984 non-null  int64
 45  minimum_maximum_nights                        13984 non-null  int64
 46  maximum_maximum_nights                        13984 non-null  int64
 47  minimum_nights_avg_ntm                        13984 non-null  float64
 48  maximum_nights_avg_ntm                        13984 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              13140 non-null  object
 51  availability_30                               13984 non-null  int64
 52  availability_60                               13984 non-null  int64
 53  availability_90                               13984 non-null  int64
 54  availability_365                              13984 non-null  int64
 55  calendar_last_scraped                         13984 non-null  object
 56  number_of_reviews                             13984 non-null  int64
 57  number_of_reviews_ltm                         13984 non-null  int64
 58  number_of_reviews_l30d                        13984 non-null  int64
 59  first_review                                  10706 non-null  object
 60  last_review                                   10706 non-null  object
 61  review_scores_rating                          10706 non-null  float64
 62  review_scores_accuracy                        10704 non-null  float64
 63  review_scores_cleanliness                     10706 non-null  float64
 64  review_scores_checkin                         10703 non-null  float64
 65  review_scores_communication                   10705 non-null  float64
 66  review_scores_location                        10703 non-null  float64
 67  review_scores_value                           10701 non-null  float64
 68  license                                       8827 non-null   object
 69  instant_bookable                              13984 non-null  object
 70  calculated_host_listings_count                13984 non-null  int64
 71  calculated_host_listings_count_entire_homes   13984 non-null  int64
 72  calculated_host_listings_count_private_rooms  13984 non-null  int64
 73  calculated_host_listings_count_shared_rooms   13984 non-null  int64
 74  reviews_per_month                             10706 non-null  float64
dtypes: float64(18), int64(21), object(36)
memory usage: 8.0+ MB

In [17]:
rating_columns = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
]
listings["avg_rating"] = listings[rating_columns].mean(axis=1)

In [18]:
listings["price"] = listings["price"].str.replace("$", "").str.replace(",", "").astype(float)

In [19]:
listings["avg_rating"].describe()

count    10706.000000
mean         4.763579
std          0.294126
min          0.571429
25%          4.704286
50%          4.837143
75%          4.920000
max          5.000000
Name: avg_rating, dtype: float64

In [20]:
drop_columns = [
    "id",
    "listing_url",
    "scrape_id",
    "last_scraped",
    "source",
    "name",
    "description",
    "neighborhood_overview",
    "picture_url",
    "host_id",
    "host_url",
    "host_name",
    "host_since",
    "host_location",
    "host_about",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_is_superhost",
    "host_thumbnail_url",
    "host_picture_url",
    "host_neighbourhood",
    "host_verifications",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood",
    "neighbourhood_cleansed",
    "neighbourhood_group_cleansed",
    "latitude",
    "longitude",
    "property_type",
    "room_type",
    "bathrooms_text",
    "amenities",
    "minimum_nights",
    "maximum_nights",
    "calendar_updated",
    "has_availability",
    "calendar_last_scraped",
    "first_review",
    "last_review",
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "license",
    "instant_bookable",
    "reviews_per_month",
]
listings = listings.drop(columns=drop_columns)

In [21]:
listings.head()

,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,price,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,...,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,avg_rating
0,1.0,1.0,2,NaN,1.0,NaN,NaN,92,92,1125,...,0,0,11,0,0,1,1,0,0,4.897143
1,7.0,7.0,2,0.5,1.0,1.0,117.0,93,93,365,...,90,180,0,0,0,3,1,2,0,NaN
2,1.0,1.0,2,1.0,1.0,1.0,95.0,1,1,1125,...,58,305,34,34,5,1,0,1,0,4.965714
3,1.0,3.0,2,NaN,NaN,NaN,NaN,92,92,1125,...,0,0,1,0,0,1,1,0,0,4.285714
4,1.0,1.0,3,NaN,2.0,NaN,NaN,92,92,1125,...,0,0,0,0,0,1,1,0,0,NaN

In [22]:
print(len(listings))
print(listings["avg_rating"].isna().sum())

listings.dropna(inplace=True)
print(len(listings))

13984
3278
6862

In [23]:
listings

,host_listings_count,host_total_listings_count,accommodates,bathrooms,bedrooms,beds,price,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,...,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,avg_rating
2,1.0,1.0,2,1.0,1.0,1.0,95.0,1,1,1125,...,58,305,34,34,5,1,0,1,0,4.965714
5,21.0,21.0,2,1.0,0.0,1.0,59.0,92,92,730,...,6,240,2,1,0,21,21,0,0,4.928571
6,2.0,2.0,6,1.0,3.0,4.0,224.0,3,6,1125,...,55,237,358,59,5,2,2,0,0,4.870000
9,1.0,1.0,2,1.0,1.0,1.0,154.0,2,2,7,...,5,5,7,5,0,1,1,0,0,4.897143
10,2.0,4.0,4,1.0,2.0,2.0,163.0,3,5,1125,...,73,73,73,17,1,1,1,0,0,4.737143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13806,1.0,3.0,2,1.0,1.0,2.0,89.0,3,15,30,...,26,37,6,1,1,1,1,0,0,4.975714
13807,1.0,4.0,4,1.0,1.0,2.0,50.0,1,1,7,...,7,7,35,35,2,1,0,1,0,4.785714
13815,2.0,2.0,2,1.0,1.0,1.0,150.0,8,10,22,...,42,42,7,1,0,1,1,0,0,4.980000
13818,8.0,8.0,4,1.0,2.0,3.0,87.0,2,2,1125,...,74,346,94,41,3,8,8,0,0,4.612857
13964,5.0,5.0,2,1.0,1.0,1.0,109.0,2,2,365,...,90,365,7,0,0,5,5,0,0,4.470000

In [24]:
def linear_regression_results(listings):
    print(f"Rows: {len(listings)}")
    Y = listings["avg_rating"]
    X = listings.drop(columns=["avg_rating"])

    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    model = LinearRegression()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print("Linear regression")
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"R-squared: {r2:.2f}")

    print("-"*30)

    print("Random model - U(0,5)")
    y_random_pred = np.random.rand(len(y_test)) * 5
    mse_random = mean_squared_error(y_test, y_random_pred)
    r2_random = r2_score(y_test, y_random_pred)
    print(f"Mean Squared Error: {mse_random:.2f}")
    print(f"R-squared: {r2_random:.2f}")

    print("-"*30)

    print("Random model - U(4,5)")
    y_random_pred = np.random.rand(len(y_test)) + 4
    mse_random = mean_squared_error(y_test, y_random_pred)
    r2_random = r2_score(y_test, y_random_pred)
    print(f"Mean Squared Error: {mse_random:.2f}")
    print(f"R-squared: {r2_random:.2f}")

In [25]:
# Use raw data with only numeric columns
linear_regression_results(listings)

Rows: 6862
Linear regression
Mean Squared Error: 0.08
R-squared: 0.14
------------------------------
Random model - U(0,5)
Mean Squared Error: 7.16
R-squared: -80.69
------------------------------
Random model - U(4,5)
Mean Squared Error: 0.24
R-squared: -1.70

## Porównanie z danymi wstępnie przetworzonymi

In [ ]:
# Used preprocessed data
listings = pd.read_csv(f'../data/{DATA_VERSION}/processed/listings.csv')
print(len(listings))
listings.dropna(inplace=True)
linear_regression_results(listings)

4195
Rows: 1828
Linear regression
Mean Squared Error: 0.58
R-squared: 0.34
------------------------------
Random model - U(0,5)
Mean Squared Error: 9.78
R-squared: -10.08
------------------------------
Random model - U(4,5)
Mean Squared Error: 21.44
R-squared: -23.28

In [ ]:
# Drop columns with many missing values
listings = pd.read_csv(f'../data/{DATA_VERSION}/processed/listings.csv')
listings.drop(columns=["price", "beds", "bathrooms"], inplace=True)
print(len(listings))
listings.dropna(inplace=True)
linear_regression_results(listings)

4195
Rows: 2008
Linear regression
Mean Squared Error: 0.37
R-squared: 0.49
------------------------------
Random model - U(0,5)
Mean Squared Error: 8.86
R-squared: -11.16
------------------------------
Random model - U(4,5)
Mean Squared Error: 21.17
R-squared: -28.04

In [ ]:
# Drop columns with missing values
listings = pd.read_csv(f'../data/{DATA_VERSION}/processed/listings.csv')
listings.drop(columns=["price", "beds", "bathrooms", "host_response_time", "host_response_rate", "host_acceptance_rate", "bedrooms"], inplace=True)
print(len(listings))
listings.dropna(inplace=True)
linear_regression_results(listings)

4195
Rows: 3220
Linear regression
Mean Squared Error: 0.32
R-squared: 0.73
------------------------------
Random model - U(0,5)
Mean Squared Error: 9.86
R-squared: -7.27
------------------------------
Random model - U(4,5)
Mean Squared Error: 21.53
R-squared: -17.08